#!/bin/sh -eu

gcp_ssh_id=${GCP_SSH_ID:-google_compute_engine}
session_name=${SESSION_NAME:-cli}
usage="Usage $0 { list | { { start | stop | conn } < workstation_id_number > } }"
ws_prefix="cli-ws-"

case $# in
  0)
    echo "$usage"
    exit 1
    ;;
  1)
    case $1 in
      list)
        gcloud compute instances list --filter name:"cli-ws"
      ;;
      *)
        echo "'$1' is not a valid command."
        echo "$usage"
        exit 2
      ;;
    esac
    ;;
  2)
    ws_id=$2
    case $1 in
      start)
        echo "Starting gcloud vm $ws_prefix$ws_id..."
        gcloud beta compute instances start \
          --zone "us-central1-a" \
          --project "cf-cli" "$ws_prefix$ws_id"
        ;;

      stop)
        echo "Stopping gcloud vm $ws_prefix$ws_id..."
        gcloud beta compute instances stop \
          --zone "us-central1-a" \
          --project "cf-cli" "$ws_prefix$ws_id"
        ;;

      conn)
        echo "Using key: $gcp_ssh_id"

        if [ "$(ssh-add -l | grep -c "$gcp_ssh_id")" -lt 1 ] ; then
          ssh-add "$HOME/.ssh/$gcp_ssh_id"
        fi

        echo "Connecting to gcloud vm $ws_prefix$ws_id..."
        set -xv
        gcloud beta compute ssh \
          --zone="us-central1-a" \
          --project="cf-cli" \
          --ssh-flag="-A -t" \
          --command="tmux new-session -s $session_name -A" "aberezovsky@$ws_prefix$ws_id"
        set +xv
        ;;
      *)
        echo "'$1' is not a valid command."
        echo "$usage"
        exit 2
        ;;
    esac
    ;;
  *)
    echo "Invalid number of args provided ($#)."
    echo "$usage"
    exit 3
    ;;
esac

